/**
 * Reads/writes a single project's manual data through a directory handle.
 *
 * Layout under the picked project directory:
 *   manual/model/model.json          (generated by papercut-processor)
 *   manual/model/meshes/<part>.json  (generated)
 *   manual/manual.json               (authored here; created on first save)
 */

import { defaultManual, type ManualDocument } from "../types/manual";
import type { MeshData, ModelData } from "../types/model";

export class ProjectSource {
  constructor(private readonly root: FileSystemDirectoryHandle) {}

  get name(): string {
    return this.root.name;
  }

  get handle(): FileSystemDirectoryHandle {
    return this.root;
  }

  async readModel(): Promise<ModelData> {
    try {
      return await this.readJson<ModelData>(["manual", "model", "model.json"]);
    } catch {
      throw new Error(
        "No exported model found (manual/model/model.json). " +
          "Run `./process <project>` or `export_manual.py` first.",
      );
    }
  }

  /** `meshPath` is a model `part.mesh`, e.g. "meshes/part_a.json". */
  readMesh(meshPath: string): Promise<MeshData> {
    return this.readJson<MeshData>(["manual", "model", ...meshPath.split("/")]);
  }

  async readManual(): Promise<ManualDocument> {
    try {
      return await this.readJson<ManualDocument>(["manual", "manual.json"]);
    } catch {
      return defaultManual();
    }
  }

  async writeManual(doc: ManualDocument): Promise<void> {
    const manualDir = await this.root.getDirectoryHandle("manual", { create: true });
    const fileHandle = await manualDir.getFileHandle("manual.json", { create: true });
    const writable = await fileHandle.createWritable();
    await writable.write(JSON.stringify(doc, null, 2));
    await writable.close();
  }

  /** Raw `project.yaml` text at the project root, or null if it doesn't exist. */
  async readProjectConfig(): Promise<string | null> {
    try {
      const fileHandle = await this.root.getFileHandle("project.yaml");
      return await (await fileHandle.getFile()).text();
    } catch {
      return null;
    }
  }

  /** Overwrite `project.yaml` with raw text (preserves whatever the caller built). */
  async writeProjectConfig(text: string): Promise<void> {
    const fileHandle = await this.root.getFileHandle("project.yaml", { create: true });
    const writable = await fileHandle.createWritable();
    await writable.write(text);
    await writable.close();
  }

  private async readJson<T>(segments: string[]): Promise<T> {
    const file = await this.resolveFile(segments);
    const text = await file.text();
    return JSON.parse(text) as T;
  }

  private async resolveFile(segments: string[]): Promise<File> {
    let dir = this.root;
    for (let i = 0; i < segments.length - 1; i += 1) {
      dir = await dir.getDirectoryHandle(segments[i]);
    }
    const fileHandle = await dir.getFileHandle(segments[segments.length - 1]);
    return fileHandle.getFile();
  }
}
