import:
  - file: https://cad.onshape.com/documents/158e84453a715565232d8169/v/ff74df2d4c036d88ad7739db/e/e0c845ac7605589343ddef62

sheets:
  - color: '*'
    name: black
    width_mm: 210
    height_mm: 100

placement:
  sheet_margin_mm: 10
  part_margin_mm: 5
  label_square_size_mm: 10

bridges:
  enable: true
  size_mm: 0.85
  min_size_all_corners_mm: 20
  min_length_extra_bridge_mm: 100
  overcut: true
  overcut_length_mm: 1.2

kerf:
  compensation: true
  offset_mm: 0.06