import:
  - file: source.step
    parts:
      balcony_side_left:
        flip_horizontal: true

overlays: {}

sheets:
  - color: "#121212"
    name: black
    width_mm: 210
    height_mm: 297
  - color: "#999999"
    name: grey
    width_mm: 210
    height_mm: 297
  - color: "#d1d1d1"
    name: white
    width_mm: 210
    height_mm: 297
  - color: "#c04931"
    name: brown
    width_mm: 210
    height_mm: 297

# sheets:
#   - color: "*"
#     name: debug
#     width_mm: 210
#     height_mm: 297

placement:
  sheet_margin_mm: 10
  part_margin_mm: 5
  label_square_size_mm: 10

bridges:
  enable: true
  size_mm: 0.5
  min_size_all_corners_mm: 20
  min_length_extra_bridge_mm: 100