import:
  - file: https://cad.onshape.com/documents/49bc2b0284d7a2d765d08b30/v/8c20db9f07712d66770c08bd/e/2e3b8605966044f4fcf220db

cut_overrides:
  balcony_side_left:
    flip_horizontal: true

engraving_overrides:
  outer_side:
    flip_horizontal: true
  outer_front:
    flip_side: true
  balcony_front:
    flip_vertical: true
    flip_side_instances: "0,2,4,6"
  balcony_side_left:
    flip_horizontal: true
    flip_side: true
  balcony_side:
    flip_vertical: true
  skirt:
    flip_vertical: true
    flip_side_instances: "1"
  roof_exit_box_door:
    flip_horizontal: true
    flip_side: true

sheets:
  - color: "#121212"
    name: black
    width_mm: 210
    height_mm: 297
  - color: "#999999"
    name: grey
    width_mm: 210
    height_mm: 297
  - color: "#d1d1d1"
    name: white
    width_mm: 210
    height_mm: 297
  - color: "#c04931"
    name: brown
    width_mm: 210
    height_mm: 297

placement:
  sheet_margin_mm: 10
  part_margin_mm: 5
  label_square_size_mm: 10

bridges:
  enable: true
  size_mm: 0.85
  min_size_all_corners_mm: 20
  min_length_extra_bridge_mm: 100
  overcut: true
  overcut_length_mm: 1.2

kerf:
  compensation: true
  offset_mm: 0.08